export {
  IMAGE_POLISH_DEFAULT_NEGATIVE_PROMPT,
  IMAGE_POLISH_DEFAULT_PROMPT,
  IMAGE_POLISH_MATERIAL_ENHANCE_NEGATIVE_PROMPT,
  IMAGE_POLISH_MATERIAL_ENHANCE_PROMPT,
  IMAGE_POLISH_NEGATIVE_PROMPT,
  IMAGE_POLISH_PROMPT,
  resolveImagePolishPrompts,
} from '../../src/constants/imagePolishPrompt';
