import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Download, Minus, Plus, RefreshCw, Send } from 'lucide-react';
import type { EditSessionDetail } from '../lib/api';
import type { EditConstraint, EditMessage } from '../types';
import { useImageEditSession, type SendEditInput } from '../hooks/useImageEditSession';
import { GenerationImageViewer, type ViewMode } from './common/GenerationImageViewer';
import { VersionTree } from './VersionTree';
import { downloadAsset, buildResultImageFilename } from '../utils/downloadAsset';
import { getGenerationCreditCost } from '../utils/generationCredits';
import { uploadImageAsset } from '../lib/api';
import { resolveAssetUrl } from '../utils/assetUrl';
import { MaskEditor } from './MaskEditor';

const constraintOptions:Array<{key:EditConstraint;label:string}>=[
  {key:'strictStructure',label:'严格保持结构'},{key:'preserveCamera',label:'保持相机'},{key:'preserveAspectRatio',label:'保持画幅'},
  {key:'materialOnly',label:'只改材质'},{key:'lightingOnly',label:'只改灯光'},{key:'furnitureOnly',label:'只改软装'},{key:'forbidNewComponents',label:'禁止增加构件'},
];

export function ImageEditSessionWorkspace({initialDetail,creditBalance,onRefreshCredits,onClose}:{initialDetail:EditSessionDetail;creditBalance:number|null;onRefreshCredits:()=>Promise<void>;onClose:()=>void}){
  const edit=useImageEditSession(initialDetail,onRefreshCredits);const [instruction,setInstruction]=useState('');const [constraints,setConstraints]=useState<Partial<Record<EditConstraint,boolean>>>({strictStructure:true,preserveCamera:true,preserveAspectRatio:true,forbidNewComponents:true});const [finalSize,setFinalSize]=useState<'2K'|'4K'>('2K');const [zoom,setZoom]=useState(1);const [retryInput,setRetryInput]=useState<SendEditInput|null>(null);const [showMaskEditor,setShowMaskEditor]=useState(false);const [maskDataUrl,setMaskDataUrl]=useState<string|null>(null);const [maskAssetId,setMaskAssetId]=useState<string|undefined>();
  const selected=edit.selectedVersion;const original=edit.detail.versions.find(version=>version.id===edit.detail.session.originalVersionId);const parent=selected?.parentVersionId?edit.detail.versions.find(version=>version.id===selected.parentVersionId):null;const selectedIndex=edit.detail.versions.findIndex(version=>version.id===selected?.id);const next=selectedIndex>=0?edit.detail.versions[selectedIndex+1]:undefined;
  const [viewerMode,setViewerMode]=useState<ViewMode>(parent?'overlay':'result');
  useEffect(()=>{setViewerMode(parent?'overlay':'result');},[parent?.id,selected?.id]);
  useEffect(()=>{setMaskDataUrl(null);setMaskAssetId(undefined);setShowMaskEditor(false);},[selected?.id]);
  const submit=async(input:SendEditInput)=>{setRetryInput(null);await edit.send(input);};
  const previewCreditCost=getGenerationCreditCost('style-render',{apiyiImageSize:'1K'});const finalCreditCost=getGenerationCreditCost('style-render',{apiyiImageSize:finalSize});
  const attachMask=async(input:SendEditInput):Promise<SendEditInput>=>{if(!maskDataUrl)return input;if(maskAssetId)return {...input,maskAssetId};const blob=await (await fetch(maskDataUrl)).blob();const asset=await uploadImageAsset(blob,`continuous-edit-mask-${selected?.id||Date.now()}.png`);setMaskAssetId(asset.id);return {...input,maskAssetId:asset.id};};
  const handleSend=()=>{const text=instruction.trim();if(!text||!selected||edit.isGenerating)return;const input:SendEditInput={instruction:text,baseVersionId:selected.id,imageSize:'1K',generationKind:'preview-edit',constraints};void attachMask(input).then(submit);};
  const handleFinalize=()=>{if(!selected||edit.isGenerating)return;const input:SendEditInput={instruction:'基于当前版本生成高清定稿，保持所有设计、结构、材质、灯光、相机和构图不变，仅提升清晰度与细节质量。',baseVersionId:selected.id,imageSize:finalSize,generationKind:'final-render',constraints:{...constraints,strictStructure:true,preserveCamera:true,preserveAspectRatio:true,forbidNewComponents:true}};void attachMask(input).then(submit);};
  const messages=useMemo(()=>{if(!edit.jobState||edit.detail.messages.some(message=>message.id===edit.jobState?.messageId))return edit.detail.messages;const optimistic:EditMessage={id:edit.jobState.messageId,sessionId:edit.detail.session.id,role:'user',content:edit.jobState.instruction,baseVersionId:edit.jobState.baseVersionId,outputVersionId:null,generationJobId:edit.jobState.jobId,status:edit.jobState.status,clientRequestId:null,errorCode:null,errorMessage:edit.jobState.error,createdAt:new Date().toISOString()};return [...edit.detail.messages,optimistic];},[edit.detail.messages,edit.detail.session.id,edit.jobState]);
  return <div className="flex min-h-0 flex-1 flex-col bg-slate-100 p-3">
    <div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-3"><button type="button" onClick={onClose} className="rounded-xl border bg-white p-2 text-slate-600"><ArrowLeft className="h-4 w-4"/></button><div><h2 className="font-bold text-slate-900">{edit.detail.session.title}</h2><p className="text-xs text-slate-500">从 V{selected?.versionNumber??0} 继续修改 · 余额 {creditBalance??'--'}</p></div></div></div>
    <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[minmax(0,1fr)_360px]">
      <main className="min-h-0 overflow-y-auto rounded-2xl border bg-white p-4">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="rounded-lg bg-blue-600 px-3 py-1 text-sm font-bold text-white">V{selected?.versionNumber??0}</span>{edit.detail.session.currentVersionId===selected?.id?<span className="text-xs font-bold text-emerald-600">当前工作版本</span>:null}</div><div className="flex items-center gap-1"><button onClick={()=>setZoom(value=>Math.max(.5,value-.25))} className="rounded-lg border p-2"><Minus className="h-4 w-4"/></button><span className="w-14 text-center text-xs">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(value=>Math.min(2,value+.25))} className="rounded-lg border p-2"><Plus className="h-4 w-4"/></button></div></div>
        <GenerationImageViewer sourceImageUrl={parent?.publicUrl} sourceImageAssetId={parent?.assetId} resultImageUrl={selected?.publicUrl} resultImageAssetId={selected?.assetId} aspectRatio={(edit.detail.session.aspectRatio==='1:1'||edit.detail.session.aspectRatio==='2:1')?edit.detail.session.aspectRatio:'16:9'} viewMode={viewerMode} onViewModeChange={setViewerMode} defaultViewMode={parent?'overlay':'result'} isGenerating={false} imageScale={zoom}/>
        <div className="mt-3"><button type="button" onClick={()=>setShowMaskEditor(value=>!value)} disabled={!selected||edit.isGenerating} className={`rounded-lg border px-3 py-2 text-xs font-bold ${maskDataUrl?'border-blue-500 bg-blue-50 text-blue-700':'bg-white text-slate-700'}`}>{showMaskEditor?'收起局部遮罩':maskDataUrl?'编辑局部遮罩':'添加局部遮罩'}</button>{maskDataUrl?<span className="ml-2 text-xs font-bold text-blue-600">遮罩将参与本轮后端生成</span>:null}</div>
        {showMaskEditor&&selected?<div className="mt-3 min-h-[420px]"><MaskEditor imageDataUrl={resolveAssetUrl(selected.publicUrl)} imageName={`V${selected.versionNumber}`} maskImageDataUrl={maskDataUrl} useFullImage={false} allowFullImage={false} onMaskChange={(nextMask)=>{setMaskDataUrl(nextMask);setMaskAssetId(undefined);}}/></div>:null}
        <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>original&&edit.chooseVersion(original.id)} className="rounded-lg border px-3 py-2 text-xs font-bold">查看原图</button><button disabled={!parent} onClick={()=>parent&&edit.chooseVersion(parent.id)} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40">父版本</button><button disabled={!next} onClick={()=>next&&edit.chooseVersion(next.id)} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40">后一版本</button><button disabled={!selected} onClick={()=>selected&&void downloadAsset({assetId:selected.assetId,url:selected.publicUrl},buildResultImageFilename({featureLabel:`连续编辑-V${selected.versionNumber}`}))} className="rounded-lg border px-3 py-2 text-xs font-bold"><Download className="mr-1 inline h-3 w-3"/>下载</button><button disabled={!selected||edit.detail.session.currentVersionId===selected.id} onClick={()=>selected&&void edit.makeCurrent(selected.id)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">设为当前工作版本</button></div>
        <p className="mt-3 rounded-xl bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">下一条指令将基于 V{selected?.versionNumber??0}，切换版本不会触发生成。</p>
      </main>
      <aside className="flex min-h-0 flex-col rounded-2xl border bg-white">
        <div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.length===0?<p className="text-center text-sm text-slate-400">输入第一条修改指令开始连续编辑</p>:messages.map(message=>{const active=edit.jobState?.messageId===message.id?edit.jobState:null;const status=active?.status||message.status;const failure=active?.error||message.errorMessage;return <div key={message.id} className="rounded-2xl bg-slate-100 p-3"><p className="text-sm text-slate-800">{message.content}</p><div className="mt-2 flex items-center justify-between text-xs"><span className={status==='failed'?'text-red-600':status==='succeeded'?'text-emerald-600':'text-blue-600'}>{readStatus(status,active?.progress)}</span>{message.outputVersionId?<span>→ V{edit.detail.versions.find(version=>version.id===message.outputVersionId)?.versionNumber}</span>:null}</div>{failure?<p className="mt-2 text-xs text-red-600">{message.errorCode?`${message.errorCode}: `:''}{failure}</p>:null}{active?.status==='failed'?<button onClick={()=>{const input:SendEditInput={instruction:active.instruction,baseVersionId:active.baseVersionId,imageSize:active.imageSize,generationKind:active.generationKind,maskAssetId:active.maskAssetId,constraints:active.constraints};setInstruction(active.instruction);setRetryInput(input);}} className="mt-2 text-xs font-bold text-blue-600"><RefreshCw className="mr-1 inline h-3 w-3"/>准备重试</button>:null}</div>;})}</div>
        <div className="border-t p-4"><textarea value={instruction} onChange={event=>setInstruction(event.target.value)} disabled={edit.isGenerating} placeholder={`描述对 V${selected?.versionNumber??0} 的修改`} className="h-24 w-full resize-none rounded-xl border p-3 text-sm outline-none focus:border-blue-500"/><div className="mt-2 flex flex-wrap gap-1.5">{constraintOptions.map(option=><button type="button" key={option.key} onClick={()=>setConstraints(value=>({...value,[option.key]:!value[option.key]}))} className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${constraints[option.key]?'border-blue-500 bg-blue-50 text-blue-700':'text-slate-500'}`}>{constraints[option.key]?<Check className="mr-1 inline h-3 w-3"/>:null}{option.label}</button>)}</div><div className="mt-3 grid gap-2"><button onClick={()=>retryInput?void submit(retryInput):handleSend()} disabled={edit.isGenerating||(!retryInput&&!instruction.trim())} className="flex items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{edit.isGenerating?<RefreshCw className="mr-2 h-4 w-4 animate-spin"/>:<Send className="mr-2 h-4 w-4"/>}{retryInput?'重试本轮':`发送修改 · 1K · ${previewCreditCost} 算力点`}</button><div className="flex gap-2"><select aria-label="高清定稿分辨率" value={finalSize} onChange={event=>setFinalSize(event.target.value as '2K'|'4K')} className="rounded-xl border px-3 text-xs"><option>2K</option><option>4K</option></select><button onClick={handleFinalize} disabled={edit.isGenerating||!selected} className="flex flex-1 items-center justify-center rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">高清定稿 · {finalSize} · {finalCreditCost} 算力点</button></div><p className="text-[11px] text-slate-500">高清定稿将以 V{selected?.versionNumber??0} 为输入创建新的子版本，不会覆盖原版本。</p></div></div>
      </aside>
    </div>
    <VersionTree versions={edit.detail.versions} selectedVersionId={selected?.id} currentVersionId={edit.detail.session.currentVersionId} onSelect={edit.chooseVersion}/>
  </div>;
}

function readStatus(status:string,progress?:number){if(status==='queued')return '排队中';if(status==='running')return `生成中 ${progress??0}%`;if(status==='succeeded')return '生成成功';if(status==='failed')return '生成失败';if(status==='cancelled')return '已取消';if(status==='timeout')return '已超时';return status;}
